name: run test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Libraries
        run: |
          pip install flake8 pytest pytest-cov robotframework pytest-md pytest-emoji

      - name: Checkout Own Repo
        uses: actions/checkout@v2
        with:
          repository: wongzc/python_calculator_zc

      - name: Start pytest Testing
        run: |
          pytest test_calculator_zc.py -v -cov --junitxml=report.xml

      - name: Compile pytest results
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: "-q"
          click-to-expand: true
          report-title: "Test Report"
      # - uses: JasonEtco/create-an-issue@v2
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     filename: .github/ISSUE_TEMPLATE.md

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action/composite@v2
      #   if: always()
      #   with:
      #     junit_files: "report.xml"
